# Generated by Django 5.2.5 on 2025-08-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='duration_weeks',
        ),
        migrations.RemoveField(
            model_name='category',
            name='price',
        ),
        migrations.AddField(
            model_name='course',
            name='duration_weeks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=-0.0, max_digits=10),
        ),
    ]
