# Generated by Django 5.2.5 on 2025-08-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_modules_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='lesson_videos/'),
        ),
    ]
