# Generated by Django 5.2.5 on 2025-08-28 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lessons_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ManyToManyField(related_name='batch', to='courses.category')),
                ('courses', models.ManyToManyField(related_name='batch', to='courses.course')),
            ],
        ),
        migrations.AlterField(
            model_name='lessons',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='courses.batch'),
        ),
        migrations.DeleteModel(
            name='Modules',
        ),
    ]
