# Generated by Django 5.2.5 on 2025-08-28 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_batch_alter_lessons_module_delete_modules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='category',
        ),
        migrations.AddField(
            model_name='batch',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='courses.category'),
        ),
    ]
