# Generated by Django 5.2.5 on 2025-08-31 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_batch_category_batch_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessons',
            old_name='module',
            new_name='batch',
        ),
    ]
