# Generated by Django 5.2.5 on 2025-08-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_rename_module_lessons_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='video',
        ),
        migrations.AddField(
            model_name='lessons',
            name='video_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
