# Generated by Django 5.2.5 on 2025-09-02 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_lessons_video_lessons_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='video_id',
        ),
    ]
